// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import { defineConfig, type PrismaConfig } from "prisma/config";

const prismaConfig = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `file:${path.join(process.cwd(), "prisma/yappd.db")}`,
  },
} satisfies PrismaConfig;

export default defineConfig(prismaConfig);
